name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: docker build -t ghcr.io/gessfred/sequel-api:latest -f ./api/Dockerfile ./api
      - run: echo "${{ secrets.REGISTRY_TOKEN }}" | docker login ghcr.io -u gessfred --password-stdin
      - run: docker push ghcr.io/gessfred/sequel-api:latest
